authors: [Epifânico, SpecterPlugins] 
name: starvel-limpadorplot
version: 0.1
main: com.specterplugins.clearplot.Starvel

commands:
  givelimpadora:
    aliases: [darlimpadora, enviarlimpadora, setlimpadora]